<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mr_gun.proto

namespace Mr_gun;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>mr_gun.GunInfo</code>
 */
class GunInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string damage = 2;</code>
     */
    private $damage = '';
    /**
     * Generated from protobuf field <code>string bulletsShot = 3;</code>
     */
    private $bulletsShot = '';
    /**
     * Generated from protobuf field <code>string totalDamage = 4;</code>
     */
    private $totalDamage = '';
    /**
     * Generated from protobuf field <code>string scatter = 5;</code>
     */
    private $scatter = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $damage
     *     @type string $bulletsShot
     *     @type string $totalDamage
     *     @type string $scatter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MrGun::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string damage = 2;</code>
     * @return string
     */
    public function getDamage()
    {
        return $this->damage;
    }

    /**
     * Generated from protobuf field <code>string damage = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDamage($var)
    {
        GPBUtil::checkString($var, True);
        $this->damage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bulletsShot = 3;</code>
     * @return string
     */
    public function getBulletsShot()
    {
        return $this->bulletsShot;
    }

    /**
     * Generated from protobuf field <code>string bulletsShot = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBulletsShot($var)
    {
        GPBUtil::checkString($var, True);
        $this->bulletsShot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string totalDamage = 4;</code>
     * @return string
     */
    public function getTotalDamage()
    {
        return $this->totalDamage;
    }

    /**
     * Generated from protobuf field <code>string totalDamage = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalDamage($var)
    {
        GPBUtil::checkString($var, True);
        $this->totalDamage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scatter = 5;</code>
     * @return string
     */
    public function getScatter()
    {
        return $this->scatter;
    }

    /**
     * Generated from protobuf field <code>string scatter = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setScatter($var)
    {
        GPBUtil::checkString($var, True);
        $this->scatter = $var;

        return $this;
    }

}

