<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mr_gun.proto

namespace Mr_gun;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>mr_gun.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sort = 1;</code>
     */
    private $sort = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sort
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MrGun::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sort = 1;</code>
     * @return string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * Generated from protobuf field <code>string sort = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkString($var, True);
        $this->sort = $var;

        return $this;
    }

}

