<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mr_gun.proto

namespace GPBMetadata;

class MrGun
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afa010a0c6d725f67756e2e70726f746f12066d725f67756e22170a0752" .
            "657175657374120c0a04736f727418012001280922620a0747756e496e66" .
            "6f120c0a046e616d65180120012809120e0a0664616d6167651802200128" .
            "0912130a0b62756c6c65747353686f7418032001280912130a0b746f7461" .
            "6c44616d616765180420012809120f0a0773636174746572180520012809" .
            "22290a055265706c7912200a0767756e496e666f18012003280b320f2e6d" .
            "725f67756e2e47756e496e666f32320a054d7247756e12290a0747657452" .
            "616e6b120f2e6d725f67756e2e526571756573741a0d2e6d725f67756e2e" .
            "5265706c79620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

